spring:
  application:
    name: main-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://studyshare.ckmxi7w0tcyn.ap-northeast-2.rds.amazonaws.com:5432/studyshare
    username: root
    password: aa123123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080